# Generated by Django 3.0.4 on 2020-03-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Attraction', 'Attraction'), ('Commercial', 'Commercial')], max_length=15)),
                ('description', models.CharField(default='Check out the AR content!', max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Trails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('waypoints', models.CharField(default='SOME WAYPOINT', max_length=150)),
                ('image', models.CharField(max_length=500)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination', to='locations.Location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origin', to='locations.Location')),
            ],
        ),
    ]
